#!/bin/sh


# sbatch --job-name="tIPVarNoise" --output Logs/IPVarNoiseTrain.txt var_noise_Class_3DCNN_parametric.sh indianPines

# sbatch --job-name="pIPVarNoise" --output Logs/a0.1-60-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 0.1 60
# sbatch --job-name="pIPVarNoise" --output Logs/a0.1-55-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 0.1 55
# sbatch --job-name="pIPVarNoise" --output Logs/a0.1-50-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 0.1 50
# sbatch --job-name="pIPVarNoise" --output Logs/a0.1-45-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 0.1 45
# sbatch --job-name="pIPVarNoise" --output Logs/a0.1-40-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 0.1 40
# sbatch --job-name="pIPVarNoise" --output Logs/a0.1-35-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 0.1 35
# sbatch --job-name="pIPVarNoise" --output Logs/a0.1-30-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 0.1 30
# sbatch --job-name="pIPVarNoise" --output Logs/a0.1-25-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 0.1 25
# sbatch --job-name="pIPVarNoise" --output Logs/a0.1-20-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 0.1 20
# sbatch --job-name="pIPVarNoise" --output Logs/a0.1-15-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 0.1 15
# sbatch --job-name="pIPVarNoise" --output Logs/a0.1-10-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 0.1 10
# sbatch --job-name="pIPVarNoise" --output Logs/a0.1-5-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 0.1 5
# sbatch --job-name="pIPVarNoise" --output Logs/a0.1-0-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 0.1 0
# sbatch --job-name="pIPVarNoise" --output Logs/a0.1--5-10-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 0.1 -5
# sbatch --job-name="pIPVarNoise" --output Logs/a0.1--10-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 0.1 -10
# sbatch --job-name="pIPVarNoise" --output Logs/a0.1--15-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 0.1 -15
# sbatch --job-name="pIPVarNoise" --output Logs/a0.1--20-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 0.1 -20

# sbatch --job-name="pIPVarNoise" --output Logs/a0.5-60-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 0.5 60
# sbatch --job-name="pIPVarNoise" --output Logs/a0.5-55-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 0.5 55
# sbatch --job-name="pIPVarNoise" --output Logs/a0.5-50-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 0.5 50
# sbatch --job-name="pIPVarNoise" --output Logs/a0.5-45-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 0.5 45
# sbatch --job-name="pIPVarNoise" --output Logs/a0.5-40-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 0.5 40
# sbatch --job-name="pIPVarNoise" --output Logs/a0.5-35-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 0.5 35
# sbatch --job-name="pIPVarNoise" --output Logs/a0.5-30-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 0.5 30
# sbatch --job-name="pIPVarNoise" --output Logs/a0.5-25-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 0.5 25
# sbatch --job-name="pIPVarNoise" --output Logs/a0.5-20-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 0.5 20
# sbatch --job-name="pIPVarNoise" --output Logs/a0.5-15-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 0.5 15
# sbatch --job-name="pIPVarNoise" --output Logs/a0.5-10-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 0.5 10
# sbatch --job-name="pIPVarNoise" --output Logs/a0.5-5-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 0.5 5
# sbatch --job-name="pIPVarNoise" --output Logs/a0.5-0-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 0.5 0
# sbatch --job-name="pIPVarNoise" --output Logs/a0.5--5-10-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 0.5 -5
# sbatch --job-name="pIPVarNoise" --output Logs/a0.5--10-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 0.5 -10
# sbatch --job-name="pIPVarNoise" --output Logs/a0.5--15-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 0.5 -15
# sbatch --job-name="pIPVarNoise" --output Logs/a0.5--20-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 0.5 -20

# sbatch --job-name="pIPVarNoise" --output Logs/a1.0-60-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 1.0 60
# sbatch --job-name="pIPVarNoise" --output Logs/a1.0-55-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 1.0 55
# sbatch --job-name="pIPVarNoise" --output Logs/a1.0-50-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 1.0 50
# sbatch --job-name="pIPVarNoise" --output Logs/a1.0-45-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 1.0 45
# sbatch --job-name="pIPVarNoise" --output Logs/a1.0-40-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 1.0 40
# sbatch --job-name="pIPVarNoise" --output Logs/a1.0-35-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 1.0 35
# sbatch --job-name="pIPVarNoise" --output Logs/a1.0-30-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 1.0 30
# sbatch --job-name="pIPVarNoise" --output Logs/a1.0-25-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 1.0 25
# sbatch --job-name="pIPVarNoise" --output Logs/a1.0-20-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 1.0 20
# sbatch --job-name="pIPVarNoise" --output Logs/a1.0-15-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 1.0 15
# sbatch --job-name="pIPVarNoise" --output Logs/a1.0-10-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 1.0 10
# sbatch --job-name="pIPVarNoise" --output Logs/a1.0-5-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 1.0 5
# sbatch --job-name="pIPVarNoise" --output Logs/a1.0-0-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 1.0 0
# sbatch --job-name="pIPVarNoise" --output Logs/a1.0--5-10-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 1.0 -5
# sbatch --job-name="pIPVarNoise" --output Logs/a1.0--10-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 1.0 -10
# sbatch --job-name="pIPVarNoise" --output Logs/a1.0--15-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 1.0 -15
# sbatch --job-name="pIPVarNoise" --output Logs/a1.0--20-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 1.0 -20

# sbatch --job-name="pIPVarNoise" --output Logs/a2.0-60-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 2.0 60
# sbatch --job-name="pIPVarNoise" --output Logs/a2.0-55-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 2.0 55
# sbatch --job-name="pIPVarNoise" --output Logs/a2.0-50-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 2.0 50
# sbatch --job-name="pIPVarNoise" --output Logs/a2.0-45-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 2.0 45
# sbatch --job-name="pIPVarNoise" --output Logs/a2.0-40-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 2.0 40
# sbatch --job-name="pIPVarNoise" --output Logs/a2.0-35-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 2.0 35
# sbatch --job-name="pIPVarNoise" --output Logs/a2.0-30-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 2.0 30
# sbatch --job-name="pIPVarNoise" --output Logs/a2.0-25-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 2.0 25
# sbatch --job-name="pIPVarNoise" --output Logs/a2.0-20-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 2.0 20
# sbatch --job-name="pIPVarNoise" --output Logs/a2.0-15-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 2.0 15
# sbatch --job-name="pIPVarNoise" --output Logs/a2.0-10-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 2.0 10
# sbatch --job-name="pIPVarNoise" --output Logs/a2.0-5-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 2.0 5
# sbatch --job-name="pIPVarNoise" --output Logs/a2.0-0-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 2.0 0
# sbatch --job-name="pIPVarNoise" --output Logs/a2.0--5-10-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 2.0 -5
# sbatch --job-name="pIPVarNoise" --output Logs/a2.0--10-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 2.0 -10
# sbatch --job-name="pIPVarNoise" --output Logs/a2.0--15-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 2.0 -15
# sbatch --job-name="pIPVarNoise" --output Logs/a2.0--20-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 2.0 -20

# sbatch --job-name="pIPVarNoise" --output Logs/a10.0-60-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 10.0 60
# sbatch --job-name="pIPVarNoise" --output Logs/a10.0-55-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 10.0 55
# sbatch --job-name="pIPVarNoise" --output Logs/a10.0-50-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 10.0 50
# sbatch --job-name="pIPVarNoise" --output Logs/a10.0-45-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 10.0 45
# sbatch --job-name="pIPVarNoise" --output Logs/a10.0-40-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 10.0 40
# sbatch --job-name="pIPVarNoise" --output Logs/a10.0-35-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 10.0 35
# sbatch --job-name="pIPVarNoise" --output Logs/a10.0-30-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 10.0 30
# sbatch --job-name="pIPVarNoise" --output Logs/a10.0-25-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 10.0 25
# sbatch --job-name="pIPVarNoise" --output Logs/a10.0-20-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 10.0 20
# sbatch --job-name="pIPVarNoise" --output Logs/a10.0-15-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 10.0 15
# sbatch --job-name="pIPVarNoise" --output Logs/a10.0-10-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 10.0 10
# sbatch --job-name="pIPVarNoise" --output Logs/a10.0-5-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 10.0 5
# sbatch --job-name="pIPVarNoise" --output Logs/a10.0-0-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 10.0 0
# sbatch --job-name="pIPVarNoise" --output Logs/a10.0--5-10-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 10.0 -5
# sbatch --job-name="pIPVarNoise" --output Logs/a10.0--10-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 10.0 -10
# sbatch --job-name="pIPVarNoise" --output Logs/a10.0--15-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 10.0 -15
# sbatch --job-name="pIPVarNoise" --output Logs/a10.0--20-IPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh indianPines 10.0 -20


# sbatch --job-name="tUPVarNoise" --output Logs/UPVarNoiseTrain.txt var_noise_Class_3DCNN_parametric.sh paviaU

# sbatch --job-name="pUPVarNoise" --output Logs/a0.1-60-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 0.1 60
# sbatch --job-name="pUPVarNoise" --output Logs/a0.1-55-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 0.1 55
# sbatch --job-name="pUPVarNoise" --output Logs/a0.1-50-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 0.1 50
# sbatch --job-name="pUPVarNoise" --output Logs/a0.1-45-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 0.1 45
# sbatch --job-name="pUPVarNoise" --output Logs/a0.1-40-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 0.1 40
# sbatch --job-name="pUPVarNoise" --output Logs/a0.1-35-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 0.1 35
# sbatch --job-name="pUPVarNoise" --output Logs/a0.1-30-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 0.1 30
# sbatch --job-name="pUPVarNoise" --output Logs/a0.1-25-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 0.1 25
# sbatch --job-name="pUPVarNoise" --output Logs/a0.1-20-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 0.1 20
# sbatch --job-name="pUPVarNoise" --output Logs/a0.1-15-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 0.1 15
# sbatch --job-name="pUPVarNoise" --output Logs/a0.1-10-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 0.1 10
# sbatch --job-name="pUPVarNoise" --output Logs/a0.1-5-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 0.1 5
# sbatch --job-name="pUPVarNoise" --output Logs/a0.1-0-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 0.1 0
# sbatch --job-name="pUPVarNoise" --output Logs/a0.1--5-10-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 0.1 -5
# sbatch --job-name="pUPVarNoise" --output Logs/a0.1--10-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 0.1 -10
# sbatch --job-name="pUPVarNoise" --output Logs/a0.1--15-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 0.1 -15
# sbatch --job-name="pUPVarNoise" --output Logs/a0.1--20-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 0.1 -20

# sbatch --job-name="pUPVarNoise" --output Logs/a0.5-60-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 0.5 60
# sbatch --job-name="pUPVarNoise" --output Logs/a0.5-55-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 0.5 55
# sbatch --job-name="pUPVarNoise" --output Logs/a0.5-50-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 0.5 50
# sbatch --job-name="pUPVarNoise" --output Logs/a0.5-45-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 0.5 45
# sbatch --job-name="pUPVarNoise" --output Logs/a0.5-40-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 0.5 40
# sbatch --job-name="pUPVarNoise" --output Logs/a0.5-35-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 0.5 35
# sbatch --job-name="pUPVarNoise" --output Logs/a0.5-30-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 0.5 30
# sbatch --job-name="pUPVarNoise" --output Logs/a0.5-25-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 0.5 25
# sbatch --job-name="pUPVarNoise" --output Logs/a0.5-20-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 0.5 20
# sbatch --job-name="pUPVarNoise" --output Logs/a0.5-15-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 0.5 15
# sbatch --job-name="pUPVarNoise" --output Logs/a0.5-10-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 0.5 10
# sbatch --job-name="pUPVarNoise" --output Logs/a0.5-5-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 0.5 5
# sbatch --job-name="pUPVarNoise" --output Logs/a0.5-0-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 0.5 0
# sbatch --job-name="pUPVarNoise" --output Logs/a0.5--5-10-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 0.5 -5
# sbatch --job-name="pUPVarNoise" --output Logs/a0.5--10-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 0.5 -10
# sbatch --job-name="pUPVarNoise" --output Logs/a0.5--15-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 0.5 -15
# sbatch --job-name="pUPVarNoise" --output Logs/a0.5--20-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 0.5 -20

# sbatch --job-name="pUPVarNoise" --output Logs/a1.0-60-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 1.0 60
# sbatch --job-name="pUPVarNoise" --output Logs/a1.0-55-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 1.0 55
# sbatch --job-name="pUPVarNoise" --output Logs/a1.0-50-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 1.0 50
# sbatch --job-name="pUPVarNoise" --output Logs/a1.0-45-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 1.0 45
# sbatch --job-name="pUPVarNoise" --output Logs/a1.0-40-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 1.0 40
# sbatch --job-name="pUPVarNoise" --output Logs/a1.0-35-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 1.0 35
# sbatch --job-name="pUPVarNoise" --output Logs/a1.0-30-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 1.0 30
# sbatch --job-name="pUPVarNoise" --output Logs/a1.0-25-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 1.0 25
# sbatch --job-name="pUPVarNoise" --output Logs/a1.0-20-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 1.0 20
# sbatch --job-name="pUPVarNoise" --output Logs/a1.0-15-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 1.0 15
# sbatch --job-name="pUPVarNoise" --output Logs/a1.0-10-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 1.0 10
# sbatch --job-name="pUPVarNoise" --output Logs/a1.0-5-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 1.0 5
# sbatch --job-name="pUPVarNoise" --output Logs/a1.0-0-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 1.0 0
# sbatch --job-name="pUPVarNoise" --output Logs/a1.0--5-10-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 1.0 -5
# sbatch --job-name="pUPVarNoise" --output Logs/a1.0--10-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 1.0 -10
# sbatch --job-name="pUPVarNoise" --output Logs/a1.0--15-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 1.0 -15
# sbatch --job-name="pUPVarNoise" --output Logs/a1.0--20-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 1.0 -20

# sbatch --job-name="pUPVarNoise" --output Logs/a2.0-60-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 2.0 60
# sbatch --job-name="pUPVarNoise" --output Logs/a2.0-55-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 2.0 55
# sbatch --job-name="pUPVarNoise" --output Logs/a2.0-50-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 2.0 50
# sbatch --job-name="pUPVarNoise" --output Logs/a2.0-45-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 2.0 45
# sbatch --job-name="pUPVarNoise" --output Logs/a2.0-40-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 2.0 40
# sbatch --job-name="pUPVarNoise" --output Logs/a2.0-35-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 2.0 35
# sbatch --job-name="pUPVarNoise" --output Logs/a2.0-30-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 2.0 30
# sbatch --job-name="pUPVarNoise" --output Logs/a2.0-25-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 2.0 25
# sbatch --job-name="pUPVarNoise" --output Logs/a2.0-20-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 2.0 20
# sbatch --job-name="pUPVarNoise" --output Logs/a2.0-15-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 2.0 15
# sbatch --job-name="pUPVarNoise" --output Logs/a2.0-10-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 2.0 10
# sbatch --job-name="pUPVarNoise" --output Logs/a2.0-5-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 2.0 5
# sbatch --job-name="pUPVarNoise" --output Logs/a2.0-0-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 2.0 0
# sbatch --job-name="pUPVarNoise" --output Logs/a2.0--5-10-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 2.0 -5
# sbatch --job-name="pUPVarNoise" --output Logs/a2.0--10-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 2.0 -10
# sbatch --job-name="pUPVarNoise" --output Logs/a2.0--15-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 2.0 -15
# sbatch --job-name="pUPVarNoise" --output Logs/a2.0--20-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 2.0 -20

# sbatch --job-name="pUPVarNoise" --output Logs/a10.0-60-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 10.0 60
# sbatch --job-name="pUPVarNoise" --output Logs/a10.0-55-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 10.0 55
# sbatch --job-name="pUPVarNoise" --output Logs/a10.0-50-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 10.0 50
# sbatch --job-name="pUPVarNoise" --output Logs/a10.0-45-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 10.0 45
# sbatch --job-name="pUPVarNoise" --output Logs/a10.0-40-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 10.0 40
# sbatch --job-name="pUPVarNoise" --output Logs/a10.0-35-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 10.0 35
# sbatch --job-name="pUPVarNoise" --output Logs/a10.0-30-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 10.0 30
# sbatch --job-name="pUPVarNoise" --output Logs/a10.0-25-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 10.0 25
# sbatch --job-name="pUPVarNoise" --output Logs/a10.0-20-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 10.0 20
# sbatch --job-name="pUPVarNoise" --output Logs/a10.0-15-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 10.0 15
# sbatch --job-name="pUPVarNoise" --output Logs/a10.0-10-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 10.0 10
# sbatch --job-name="pUPVarNoise" --output Logs/a10.0-5-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 10.0 5
# sbatch --job-name="pUPVarNoise" --output Logs/a10.0-0-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 10.0 0
# sbatch --job-name="pUPVarNoise" --output Logs/a10.0--5-10-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 10.0 -5
# sbatch --job-name="pUPVarNoise" --output Logs/a10.0--10-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 10.0 -10
# sbatch --job-name="pUPVarNoise" --output Logs/a10.0--15-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 10.0 -15
# sbatch --job-name="pUPVarNoise" --output Logs/a10.0--20-UPVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh paviaU 10.0 -20


sbatch --job-name="tSALVarNoise" --output Logs/SALVarNoiseTrain.txt var_noise_Class_3DCNN_parametric.sh salinas

sbatch --job-name="pSALVarNoise" --output Logs/a0.1-60-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 0.1 60
sbatch --job-name="pSALVarNoise" --output Logs/a0.1-55-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 0.1 55
sbatch --job-name="pSALVarNoise" --output Logs/a0.1-50-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 0.1 50
sbatch --job-name="pSALVarNoise" --output Logs/a0.1-45-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 0.1 45
sbatch --job-name="pSALVarNoise" --output Logs/a0.1-40-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 0.1 40
sbatch --job-name="pSALVarNoise" --output Logs/a0.1-35-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 0.1 35
sbatch --job-name="pSALVarNoise" --output Logs/a0.1-30-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 0.1 30
sbatch --job-name="pSALVarNoise" --output Logs/a0.1-25-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 0.1 25
sbatch --job-name="pSALVarNoise" --output Logs/a0.1-20-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 0.1 20
sbatch --job-name="pSALVarNoise" --output Logs/a0.1-15-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 0.1 15
sbatch --job-name="pSALVarNoise" --output Logs/a0.1-10-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 0.1 10
sbatch --job-name="pSALVarNoise" --output Logs/a0.1-5-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 0.1 5
sbatch --job-name="pSALVarNoise" --output Logs/a0.1-0-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 0.1 0
sbatch --job-name="pSALVarNoise" --output Logs/a0.1--5-10-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 0.1 -5
sbatch --job-name="pSALVarNoise" --output Logs/a0.1--10-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 0.1 -10
sbatch --job-name="pSALVarNoise" --output Logs/a0.1--15-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 0.1 -15
sbatch --job-name="pSALVarNoise" --output Logs/a0.1--20-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 0.1 -20

sbatch --job-name="pSALVarNoise" --output Logs/a0.5-60-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 0.5 60
sbatch --job-name="pSALVarNoise" --output Logs/a0.5-55-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 0.5 55
sbatch --job-name="pSALVarNoise" --output Logs/a0.5-50-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 0.5 50
sbatch --job-name="pSALVarNoise" --output Logs/a0.5-45-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 0.5 45
sbatch --job-name="pSALVarNoise" --output Logs/a0.5-40-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 0.5 40
sbatch --job-name="pSALVarNoise" --output Logs/a0.5-35-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 0.5 35
sbatch --job-name="pSALVarNoise" --output Logs/a0.5-30-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 0.5 30
sbatch --job-name="pSALVarNoise" --output Logs/a0.5-25-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 0.5 25
sbatch --job-name="pSALVarNoise" --output Logs/a0.5-20-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 0.5 20
sbatch --job-name="pSALVarNoise" --output Logs/a0.5-15-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 0.5 15
sbatch --job-name="pSALVarNoise" --output Logs/a0.5-10-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 0.5 10
sbatch --job-name="pSALVarNoise" --output Logs/a0.5-5-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 0.5 5
sbatch --job-name="pSALVarNoise" --output Logs/a0.5-0-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 0.5 0
sbatch --job-name="pSALVarNoise" --output Logs/a0.5--5-10-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 0.5 -5
sbatch --job-name="pSALVarNoise" --output Logs/a0.5--10-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 0.5 -10
sbatch --job-name="pSALVarNoise" --output Logs/a0.5--15-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 0.5 -15
sbatch --job-name="pSALVarNoise" --output Logs/a0.5--20-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 0.5 -20

sbatch --job-name="pSALVarNoise" --output Logs/a1.0-60-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 1.0 60
sbatch --job-name="pSALVarNoise" --output Logs/a1.0-55-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 1.0 55
sbatch --job-name="pSALVarNoise" --output Logs/a1.0-50-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 1.0 50
sbatch --job-name="pSALVarNoise" --output Logs/a1.0-45-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 1.0 45
sbatch --job-name="pSALVarNoise" --output Logs/a1.0-40-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 1.0 40
sbatch --job-name="pSALVarNoise" --output Logs/a1.0-35-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 1.0 35
sbatch --job-name="pSALVarNoise" --output Logs/a1.0-30-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 1.0 30
sbatch --job-name="pSALVarNoise" --output Logs/a1.0-25-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 1.0 25
sbatch --job-name="pSALVarNoise" --output Logs/a1.0-20-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 1.0 20
sbatch --job-name="pSALVarNoise" --output Logs/a1.0-15-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 1.0 15
sbatch --job-name="pSALVarNoise" --output Logs/a1.0-10-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 1.0 10
sbatch --job-name="pSALVarNoise" --output Logs/a1.0-5-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 1.0 5
sbatch --job-name="pSALVarNoise" --output Logs/a1.0-0-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 1.0 0
sbatch --job-name="pSALVarNoise" --output Logs/a1.0--5-10-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 1.0 -5
sbatch --job-name="pSALVarNoise" --output Logs/a1.0--10-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 1.0 -10
sbatch --job-name="pSALVarNoise" --output Logs/a1.0--15-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 1.0 -15
sbatch --job-name="pSALVarNoise" --output Logs/a1.0--20-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 1.0 -20

sbatch --job-name="pSALVarNoise" --output Logs/a2.0-60-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 2.0 60
sbatch --job-name="pSALVarNoise" --output Logs/a2.0-55-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 2.0 55
sbatch --job-name="pSALVarNoise" --output Logs/a2.0-50-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 2.0 50
sbatch --job-name="pSALVarNoise" --output Logs/a2.0-45-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 2.0 45
sbatch --job-name="pSALVarNoise" --output Logs/a2.0-40-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 2.0 40
sbatch --job-name="pSALVarNoise" --output Logs/a2.0-35-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 2.0 35
sbatch --job-name="pSALVarNoise" --output Logs/a2.0-30-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 2.0 30
sbatch --job-name="pSALVarNoise" --output Logs/a2.0-25-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 2.0 25
sbatch --job-name="pSALVarNoise" --output Logs/a2.0-20-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 2.0 20
sbatch --job-name="pSALVarNoise" --output Logs/a2.0-15-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 2.0 15
sbatch --job-name="pSALVarNoise" --output Logs/a2.0-10-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 2.0 10
sbatch --job-name="pSALVarNoise" --output Logs/a2.0-5-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 2.0 5
sbatch --job-name="pSALVarNoise" --output Logs/a2.0-0-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 2.0 0
sbatch --job-name="pSALVarNoise" --output Logs/a2.0--5-10-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 2.0 -5
sbatch --job-name="pSALVarNoise" --output Logs/a2.0--10-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 2.0 -10
sbatch --job-name="pSALVarNoise" --output Logs/a2.0--15-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 2.0 -15
sbatch --job-name="pSALVarNoise" --output Logs/a2.0--20-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 2.0 -20

sbatch --job-name="pSALVarNoise" --output Logs/a10.0-60-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 10.0 60
sbatch --job-name="pSALVarNoise" --output Logs/a10.0-55-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 10.0 55
sbatch --job-name="pSALVarNoise" --output Logs/a10.0-50-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 10.0 50
sbatch --job-name="pSALVarNoise" --output Logs/a10.0-45-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 10.0 45
sbatch --job-name="pSALVarNoise" --output Logs/a10.0-40-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 10.0 40
sbatch --job-name="pSALVarNoise" --output Logs/a10.0-35-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 10.0 35
sbatch --job-name="pSALVarNoise" --output Logs/a10.0-30-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 10.0 30
sbatch --job-name="pSALVarNoise" --output Logs/a10.0-25-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 10.0 25
sbatch --job-name="pSALVarNoise" --output Logs/a10.0-20-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 10.0 20
sbatch --job-name="pSALVarNoise" --output Logs/a10.0-15-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 10.0 15
sbatch --job-name="pSALVarNoise" --output Logs/a10.0-10-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 10.0 10
sbatch --job-name="pSALVarNoise" --output Logs/a10.0-5-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 10.0 5
sbatch --job-name="pSALVarNoise" --output Logs/a10.0-0-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 10.0 0
sbatch --job-name="pSALVarNoise" --output Logs/a10.0--5-10-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 10.0 -5
sbatch --job-name="pSALVarNoise" --output Logs/a10.0--10-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 10.0 -10
sbatch --job-name="pSALVarNoise" --output Logs/a10.0--15-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 10.0 -15
sbatch --job-name="pSALVarNoise" --output Logs/a10.0--20-SALVarNoisePredict.txt var_noise_Class_3DCNN_predict_parametric.sh salinas 10.0 -20
